project:
  type: website

website:
  title: "Gaetano Scaduto"

format:
  html:
    theme: cosmo
    include-in-header:
      text: |
        <meta http-equiv="refresh" content="0; url="https://gaetanoscaduto.github.io/">
        <link rel="canonical" href="https://gaetanoscaduto.github.io/">