---
title: "Publications"
---

Here you can find the list of the papers I worked on. If you need further info, just reach out and I'll be happy to share more! You can also find the most updated list of my publications on [my profile in google scholar](https://scholar.google.it/citations?user=g52GJngAAAAJ&hl=it&oi=ao).

If your institution provides access to the papers, please download them from the websites linked with the authors' names. This helps with my stats.

If you do not have access, please reach out via email (gaetano.scaduto\@unimib.it or gaetanoscaduto1999\@gmail.com) and I will be very glad to provide you with a copy of the manuscript.

## Published/Accepted papers

-   Scaduto, G. (2025). Politicultural Linking: Inferences between Political and Apolitical Traits. Accepted in Public Opinion Quarterly.

-   [Scaduto, G, Negri, F. (2024)](https://www.rivisteweb.%20it/doi/10.3270/115244). The Pundit Paradox: Exploring the Mismatch between Supply and Demand in Italian Political Talk Show Guests. Comunicazione Politica.

<!-- -->

-   [Scaduto, G., Negri, F. (2024)](https://doi.org/10.%201080/13608746.2024.2411539). Food for (political) thought: political inferences from apolitical cues and their social consequences in Italy. South European Society and Politics, 1–30.

    -   Awarded "Best paper by a Junior Researcher" by the Italian Political Communication Association (ASSOCOMPOL) in 2024.

<!-- -->

-   [Mancosu, M., Scaduto, G. (2024).](https://www.tandfonline.com/doi/full/10.1080/15205436.2024.2351980)"Crowds and Smiles: Visual Opportunity Structures and the Communication of European Political Leaders during the Covid-19 Pandemic". Mass Communication & Society. *Mass Communication and Society*, 1-26.

    -   My first paper, but on steroids.

<!--         <p><i class="fas fa-download pr-1 fa-fw"></i><a href=publications/Mancosu_Scaduto_2024.pdf target=_blank> Click here to download</a>.</p> -->

-   [Bertero, A, Scaduto, G](https://oaj.fupress.net/index.php/qoe/article/view/14224). (2023). A midsummer night's dream: political communication during the Italian 2022 electoral campaign. Italian Journal of Electoral Studies QOE-IJES.

    -   A paper that deals with analyzing the 2022 electoral campaign in Italy from a political communication POV.

<!--         <p><i class="fas fa-download pr-1 fa-fw"></i><a href=publications/Bertero_Scaduto_2023.pdf target=_blank> Click here to download</a>.</p> -->

-   [Scaduto, G., Mancosu, M. (2022).](https://www.rivisteweb.it/doi/10.3270/104851) Lacrime di coccodrillo? Variazioni nel contenuto visuale su Instagram dei politici populisti e mainstream durante la pandemia. *Comunicazione politica*, *23*(2), 255-276.

    -   The very first paper I ever worked on. Tries to investigate one simple question: do political leader smile less on Instagram while there are more deaths by Covid? And are there differences between populist and non-populist?

<!--         <p><i class="fas fa-download pr-1 fa-fw"></i><a href=publications/Scaduto_Mancosu_2022.pdf target=_blank> Click here to download</a>.</p> -->

-   [Scaduto, G. (2022)](https://www.rivisteweb.it/doi/10.1424/104525). Gli algoritmi di computer vision: una guida all'uso per le scienze politiche e sociali. *Polis*, *36*(2), 315-332.

    -   Dealing with IA and machine learning before ChatGTP, Midjourneys and all those guys were cool.

<!--         <p><i class="fas fa-download pr-1 fa-fw"></i><a href=publications/Scaduto_2022.pdf target=_blank> Click here to download</a>.</p> -->

## Working papers/Under review

-   Scaduto, G., Negri, F. Exploring the factors associated with political inferences from food preferences.

    -   Accepted for presentation at ECPR 2023 General Conference, AssoComPol 2023 Conference, SISP 2023 Conference. My first experimental paper dealing with why we think vegans are leftists and stuff like that.

-   Respi, C., Gui, M., Legnante, G., Pizzul, D., Gerosa, T., Scaduto, G. & Serini, M. Privacy protection as an exception in the digital inequality framework (and why this is not good news)

    -   Presented at VDATA Final Conference in Pavia (IT), 7-8 September 2023. I am working ion the results section of this paper. It is my first experience with doing structural equation modeling. I don't think it will be the last :)

## Other stuff I wrote

-   [My MA thesis](https://github.com/gaetanoscaduto/Papers-Others/blob/Papers/TESI%20_merged.pdf)! (In italian) "Un paese di musichette mentre fuori c'è la morte? Indagine sulla comunicazione dei politici italiani su Instagram durante la pandemia di Covid-19". Thesis supervisor: prof. Moreno Mancosu.

-   [My BA thesis](https://github.com/gaetanoscaduto/Papers-Others/blob/Papers/Tesi%20triennale.pdf)! (In italian) "Teoria della scelta sociale". Thesis supervisor: prof. Giacomo Como.

-   You can find several light-reading articles about politics and other stuff on the [personal blog](https://nienteditwee.blogspot.com/) \[in Italian\] I used to write on a couple of years ago. Among those you'll find...

    -   Three super-long articles about the Conte II government crisis [\[Part 1\]](https://nienteditwee.blogspot.com/2021/01/capire-la-crisi-racconto-autoironico.html), [\[Part 2\]](https://nienteditwee.blogspot.com/2021/02/lintermezzo-dal-conte-ter-mario-draghi.html), [\[Part 3\]](https://nienteditwee.blogspot.com/2021/02/continuare-capire-la-crisi.html).

    -   A super-duper-long article about [Bernie Sanders' 2020 presidential campaign](https://nienteditwee.blogspot.com/2019/12/).

    -   A super-duper-looper long article about [my fake troll run for school council in 2016](https://nienteditwee.blogspot.com/2016/10/).

-   In April 2024 I gave a recreational presentation about "Fermat's Last Theorem" at the M2P Staff Meeting (University of Antwerp). You can find the slides, summarizing the story, [here](https://github.com/gaetanoscaduto/other-stuff/blob/main/Fermat%E2%80%99s%20Last%20Problem%20(2).pdf).
